version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: some-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
